
server:
  port: 8080

spring:
  datasource:
    #url: jdbc:h2:./data/db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    url: jdbc:mysql://localhost:3306/user_registration
    username: root
    password: Sandhya@123
    #driverClassName: org.h2.Driver

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  #h2:
    #console:
      #enabled: true
  security:
    oauth2:
      client:
        registration:
          api-client-oidc:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: api-client-oidc
          api-client-authorization-code:
            provider: spring
            client-id: api-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: api.read
            client-name: api-client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000
