
server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:./data/db
    username: sa
    password: 
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true